server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy API calls to backend services (resolved by K8s DNS)
    location /products {
        proxy_pass http://category-product-service:5001;
        proxy_set_header Host $host;
    }
    location /categories {
        proxy_pass http://category-product-service:5001;
        proxy_set_header Host $host;
    }
    location /orders {
        proxy_pass http://order-service:3002;
        proxy_set_header Host $host;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
